Update DevOps-pipeline_grupp4_EU.yml

diff --git a/.github/workflows/DevOps-pipeline_grupp4_EU.yml b/.github/workflows/DevOps-pipeline_grupp4_EU.yml
--- a/.github/workflows/DevOps-pipeline_grupp4_EU.yml
+++ b/.github/workflows/DevOps-pipeline_grupp4_EU.yml
@@ -39,6 +39,7 @@ jobs:
             echo "✅ Integration test OK"
           else
             echo "❌ Integration test failed"
+            exit 1
           fi
 
   building-docker-image:
@@ -56,17 +57,28 @@ jobs:
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
-            password: ${{ secrets.test3 }}
+            password: ${{ secrets.DOCKERHUB_TOKEN }}
   
         - name: Build and push to Docker Hub
           uses: docker/build-push-action@v6
           with:
-            context: .
-            file: ./Dockerfile
+            context: ./weather_app
+            file: ./weather_app/dockerfile
             push: true
             tags: |
-              studenteriksti/automation_and_devops_course:latest
-              studenteriksti/automation_and_devops_course:1.5
+              studenteriksti/devops-pipeline_grupp4_eu:latest
+              studenteriksti/devops-pipeline_grupp4_eu:1.5
+
+        - name: Confirm image pushed
+          if: success()
+          run: echo "✅ Image successfully built and pushed"
+
+        - name: Report failure
+          if: failure()
+          run: echo "❌ Docker image build or pushed failed"
+       
+       
+            
 
 
            
